force-app/main/default/objects/Rental_Unit__c/Rental_Unit__c.object-meta.xml
<CustomObject>
    <description>Part of the new b2c initiative- renting out unused hardware!</description>
    <label>Rental Unit</label>
    <nameField>
        <displayFormat>BIKE-{00000}</displayFormat>
        <label>Rental Unit No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Unit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Rental Units</relationshipLabel>
    <relationshipName>Rental_Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/rentalRideUtils.cls
public with sharing class rentalRideUtils {
    @AuraEnabled(cacheable=true)
    public static Product__c rentalProductDetails(string rentalUnitID){
        Rental_Unit__c rental = [select product__r.Picture_URL__c, product__r.Id, product__r.Name FROM Rental_Unit__c WHERE id = :rentalUnitID];
        Product__c returnProd = new Product__c(Picture_URL__c=rental.product__r.Picture_URL__c, Id=rental.product__r.Id, Name=rental.product__r.Name);
        return returnProd;
    }
}